default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: learnrails_development

test:
  <<: *default
  database: learnrails_test

production:
  <<: *default
  database: learnrails_production
  username: learnrails
  password: <%= ENV['APP_DATABASE_PASSWORD'] %>
  host: localhost
  port: 5432
